import type { Metadata } from "next";
import { Geist, Geist_Mono, Federo } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/navbar/navbar";
import 'flowbite';
import 'flowbite-react';
import 'tailwindcss/tailwind.css';
import Footer from "@/components/footer/footer";
import { ReactNode } from "react";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
// import "flowbite/dist/flowbite.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const federo = Federo({
  weight: '400',
  subsets: ['latin'],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
  params: { locale: string };
}

export default async function RootLayout({ children, params: { locale } }: Props) {

  const messages = await getMessages({ locale });




  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextIntlClientProvider messages={messages }>

          <Navbar />
          {children}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>


  );
}
